# Generated by Django 3.1.8 on 2022-12-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='images/'),
        ),
    ]
